[versions]
lombok = "1.18.46"
velocity = "3.4.0-SNAPSHOT"
jetbrains-annotations = "26.1.0"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
